issuer: http://127.0.0.1:5556/dex

storage:
  type: sqlite3
  config:
    file: dex.db

web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]

telemetry:
  http: 0.0.0.0:5558

staticClients:
  - id: webtech-frontend
    redirectURIs:
      - "http://localhost:3000"
    name: "WetTech Front End Chat Server"
    public: true

connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: d3251fa7f4e5447ef1ea
      clientSecret: 5eefc0c80c7f44ecb5a787d0d545a1c119938354
      redirectURI: http://127.0.0.1:5556/dex/callback

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
